# -- 코드를 입력하
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.SCORE
FROM REST_INFO I LEFT JOIN (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID) R ON I.REST_ID=R.REST_ID
WHERE I.ADDRESS LIKE '서울%' AND R.SCORE IS NOT NULL
ORDER BY R.SCORE DESC, I.FAVORITES DESC