# SELECT *
# FROM USER_INFO
# WHERE GENDER IS NOT NULL

SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, U.GENDER, COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER