-- 코드를 입력하세요
WITH J AS (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR),
FINAL AS (
SELECT F.SHIPMENT_ID, F.FLAVOR, (F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F JOIN J ON J.FLAVOR = F.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3)

SELECT FLAVOR FROM FINAL;

# SELECT FLAVOR
# FROM
#     (
#         SELECT *
#         FROM JULY
#         UNION ALL
#         SELECT *
#         FROM FIRST_HALF
#     ) A
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3
# ;