SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
(SELECT MEMBER_PROFILE.MEMBER_ID, 
       MEMBER_NAME,
       COUNT(REVIEW_TEXT) AS REVIEW_NUM,
       RANK() OVER(ORDER BY COUNT(REVIEW_TEXT) DESC) AS RANKING
FROM MEMBER_PROFILE
LEFT JOIN REST_REVIEW ON MEMBER_PROFILE.MEMBER_ID = REST_REVIEW.MEMBER_ID
GROUP BY MEMBER_PROFILE.MEMBER_ID) AS TEMP
RIGHT JOIN REST_REVIEW ON TEMP.MEMBER_ID = REST_REVIEW.MEMBER_ID
WHERE RANKING = 1
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC