# 2021년에 가입한 전체 회원들 중
# 상품을 구매한 회원수와
# 상품을 구매한 회원의 비율 (=2021년에 가입한 회원 중 구매한 회원수 / 2021년에 가입한 전체 회원 수)
# 을 년, 월 별로 출력
# 비율은 소수점 두번째자리에서 반올림
# 전체 결과는 년을 기준으로 오름차순, 같다면 월을 기준으로 오름차순 정렬

WITH SUM AS (SELECT * 
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'),
ENT AS (SELECT COUNT(*) FROM SUM)


# select YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT(O.USER_ID)) 
# # select *
# from ONLINE_SALE O LEFT JOIN SUM ON O.USER_ID = SUM.USER_ID
# WHERE SUM.JOINED IS NOT NULL
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH


SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT(O.USER_ID)) / (select * from ENT), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O LEFT JOIN SUM ON O.USER_ID = SUM.USER_ID 
WHERE SUM.JOINED IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH