-- 코드를 입력하세요
WITH TEMP AS (
SELECT HOST_ID
FROM PLACES
GROUP BY HOST_ID
HAVING (COUNT(*) > 1))

SELECT P.ID ID, P.NAME NAME, P.HOST_ID HOST_ID
FROM PLACES P, TEMP T
WHERE P.HOST_ID = T.HOST_ID
ORDER BY ID