WITH C AS (SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = '트럭')
, RES AS (
# , P AS (
#     SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# WHERE CAR_TYPE = '트럭'
# 5 8 15
SELECT H.HISTORY_ID,
CASE WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.85
WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.92
WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * 0.95
ELSE C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE IS NOT NULL)

select HISTORY_ID, CAST(FEE AS signed integer) AS FEE from RES
order by FEE DESC, HISTORY_ID DESC
# CAST(a AS signed integer)

