-- 코드를 입력하세요
# 생산일자가 2022년 5월인 식품들
WITH MAY AS (
SELECT ORDER_ID, PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE PRODUCE_DATE LIKE '%2022-05%'
GROUP BY PRODUCT_ID)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, MAY.AMOUNT * P.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN MAY ON P.PRODUCT_ID = MAY.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;

# select * from MA/Y