-- 코드를 입력하세요
SELECT H.CAR_ID
# SELECT *
FROM CAR_RENTAL_COMPANY_CAR C RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND H.START_DATE LIKE '2022-10%'
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;