WITH RES AS (
    SELECT MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
)

SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, RES
WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유') AND F.PRICE = RES.PRICE
GROUP BY CATEGORY
ORDER BY PRICE DESC;